### PR TITLE
Refactor unused function parameters in "Group": Integration [8 Files]

### PR DESCRIPTION
**Pull request by grace43**
Type of change:
Instead of using the _LOGGER solution, I researched and found a better solution by using the No-Op operation. 
The functional signature has not been changed.
Went for this solution because it doesn't introduce additional overhead or clutter logs.

- [x] Code quality improvements to existing code or addition of tests

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] The code has been formatted using Black (`black --fast homeassistant tests`)
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

### CODE REVIEW

**Review by OscarSanner — APPROVED** [review]
Looks good. One thought: For each function we do this, the function gets longer. It also increases the cognitive complexity. We could mitigate this by creating a function called no_op() or similar, and make it globally reachable, we could call the function each time instead of duplicating these lines in each function.

But its not a life or death change.

**Comment by OscarSanner** [comment]
Look at comment and decide before merge!

**Comment by grace43** [comment]
I agree, let me try and fix that

**Comment by grace43** [comment]
> Look at comment and decide before merge!

I implemented the change and created the function in the util file, I went ahead and removed the 'pass' statement because it does nothing and Pylint was complaining about it. Now in each file I just call the function

**Pull request merged**
